apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc-hammerdb
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/TPC-Council/HammerDB
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7.9.2009
      dockerfilePath: Docker/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: hammerdb:latest
  triggers:
    - type: ConfigChange
