apiVersion: apps/v1
kind: Deployment
metadata:
  name: hammerdb
  labels:
    component: hammerdb
spec:
  selector:
    matchLabels:
      component: hammerdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: hammerdb
    spec:
      containers:
        - image: ghcr.io/cci-moc/k-hammer:nightly
          name: hammerdb
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/bin/sleep"
          args:
            - "10000"
          env:
            - name: "TMP"
              value: "/tmp"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: vol-hammer-scripts
              mountPath: /home/hammerdb/HammerDB-4.5/maria_ephemeral_tprocc_build.tcl
              subPath: maria_ephemeral_tprocc_build.tcl
            - name: vol-hammer-scripts
              mountPath: /home/hammerdb/HammerDB-4.5/maria_ephemeral_tprocc_run.tcl
              subPath: maria_ephemeral_tprocc_run.tcl
            - name: vol-hammer-scripts
              mountPath: /home/hammerdb/HammerDB-4.5/maria_tprocc_build.tcl
              subPath: maria_tprocc_build.tcl
            - name: vol-hammer-scripts
              mountPath: /home/hammerdb/HammerDB-4.5/maria_tprocc_run.tcl
              subPath: maria_tprocc_run.tcl
      volumes:
        - name: vol-hammer-scripts
          configMap:
            name: cm-k-hammer
