apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hammerdb

resources:
  # - bc-hammerdb.yaml
  # - is-hammerdb.yaml
  - deployment-mariadb.yaml
  - deployment-mariadb-ssd.yaml
  - deployment-mariadb-ephemeral.yaml
  - deployment-hammerdb.yaml
  - pvc-mariadb.yaml
  - pvc-mariadb-ssd.yaml
  - svc-mariadb.yaml
  - svc-mariadb-ssd.yaml
  - svc-mariadb-ephemeral.yaml

configMapGenerator:
  - name: cm-k-hammer
    files:
      - my.cnf=mariadb-conf/etc-mysql-my.cnf
      - mariadb.cnf=mariadb-conf/etc-mysql-mariadb.cnf
      - mysqld_safe_syslog.cnf=mariadb-conf/etc-mysql-conf.d-mysqld_safe_syslog.cnf
      - maria_ephemeral_tprocc_build.tcl=hammerdb-scripts/maria_ephemeral_tprocc_build.tcl
      - maria_ephemeral_tprocc_run.tcl=hammerdb-scripts/maria_ephemeral_tprocc_run.tcl
      - maria_tprocc_build.tcl=hammerdb-scripts/maria_tprocc_build.tcl
      - maria_tprocc_run.tcl=hammerdb-scripts/maria_tprocc_run.tcl
      - maria_ssd_tprocc_build.tcl=hammerdb-scripts/maria_ssd_tprocc_build.tcl
      - maria_ssd_tprocc_run.tcl=hammerdb-scripts/maria_ssd_tprocc_run.tcl

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
