apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hammerdb
namespace: hammerdb

resources:
  # - bc-hammerdb.yaml
  # - is-hammerdb.yaml
  - deployment-mariadb.yaml
  - ns-hammerdb.yaml
  - pvc-mariadb.yaml
  - svc-mariadb.yaml
  - deployment-hammerdb.yaml

configMapGenerator:
  - name: cm-mariadb-conf
    files:
      - my.cnf=mariadb-conf/etc-mysql-my.cnf
      - mariadb.cnf=mariadb-conf/etc-mysql-mariadb.cnf
      - mysqld_safe_syslog.cnf=mariadb-conf/etc-mysql-conf.d-mysqld_safe_syslog.cnf

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
